//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platnosc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Platnosc()
        {
            this.Faktura = new HashSet<Faktura>();
        }
    
        public int IdPlatnosci { get; set; }
        public int IdKlienta { get; set; }
        public int IdSposobuPlatnosci { get; set; }
        public int IdStatusuPlatnosci { get; set; }
        public Nullable<System.DateTime> DataPlatnosci { get; set; }
        public decimal Kwota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktura> Faktura { get; set; }
        public virtual Klient Klient { get; set; }
        public virtual SposobPlatnosci SposobPlatnosci { get; set; }
        public virtual StatusPlatnosci StatusPlatnosci { get; set; }
    }
}
