//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokoj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pokoj()
        {
            this.Rezerwacja = new HashSet<Rezerwacja>();
        }
    
        public int IdPokoju { get; set; }
        public string NrPokoju { get; set; }
        public int IdTypuPokoju { get; set; }
        public int IdKlasyPokoju { get; set; }
    
        public virtual KlasaPokoju KlasaPokoju { get; set; }
        public virtual TypPokoju TypPokoju { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezerwacja> Rezerwacja { get; set; }
    }
}
