
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MVVMFirma.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Pokoj
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Pokoj()
    {

        this.RezerwacjaPokoje = new HashSet<RezerwacjaPokoje>();

    }


    public int IdPokoju { get; set; }

    public string NrPokoju { get; set; }

    public int IdTypuPokoju { get; set; }

    public int IdKlasyPokoju { get; set; }

    public int IdStatusuPokoju { get; set; }

    public int IdPietra { get; set; }



    public virtual KlasaPokoju KlasaPokoju { get; set; }

    public virtual Pietro Pietro { get; set; }

    public virtual StatusPokoju StatusPokoju { get; set; }

    public virtual TypPokoju TypPokoju { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RezerwacjaPokoje> RezerwacjaPokoje { get; set; }

}

}
