//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerwacja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezerwacja()
        {
            this.Faktura = new HashSet<Faktura>();
        }
    
        public int IdRezerwacji { get; set; }
        public int IdKlienta { get; set; }
        public int IdPokoju { get; set; }
        public int IdPracownika { get; set; }
        public string IloscDoroslych { get; set; }
        public string IloscDzieci { get; set; }
        public string IloscZwierzat { get; set; }
        public System.DateTime DataZameldowania { get; set; }
        public System.DateTime DataWymeldowania { get; set; }
        public System.DateTime DataRezerwacji { get; set; }
        public string Uwagi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktura> Faktura { get; set; }
        public virtual Klient Klient { get; set; }
        public virtual Pokoj Pokoj { get; set; }
        public virtual Pracownik Pracownik { get; set; }
    }
}
